### ISSUE TITLE
MySQL Table Creation

### ISSUE THREAD

**Issue by Travis-Owens** [Travis-Owens/Service-Status-Checker#1]
Create MySQL scheme with that includes:

  - service_id      -   int (ai)
  - service_name    -   text
  - service_type    -   text
  - service_address -   text
  - last_checked_status - boolean
  - notification_email  - boolean
  - notification_sms    - boolean
  - email           - text
  - phone_number    - text

For now columns should allow null values, and the script should act accordingly when NULL is encountered.

**Comment by mathisve** [comment]
Consider the MySQL table creation done.

This is what a table looks like:

1. service_id - int (ai)
2. service_created - timestamp
3. last_updated - timestamp
4. service_name - text
5. service_type - text
6. service_address - text
7. last_checked_status - boolean
8. notification_email - boolean
9. notification_sms - boolean
10. email - text
11. phone_number - text

I'm gonna do the db integration next tomorrow! Ill keep you posted!

**Comment by mathisve** [comment]
Found bug:

It prints the "table allready exists" error message
Even though the code should prevent this from doing it.

```
except Exception as e:
	if("(1050," in e): #1050 is warning code for table allready exists
		print("Found table!")
	else:
		print(e) 
```

I have tried but can't seem to figure out what the hell is going on

**Comment by Travis-Owens** [comment]
If you want to be able to detect if the table exist with that method, you need to remove the "IF NOT EXIST". Additionally, we should handle pyMySQL exceptions separately from general exceptions. I believe that the code below accomplishes what you wanted.

```
with connection.cursor() as cursor:
	try:
		cursor.execute("CREATE TABLE services (service_id int NOT NULL AUTO_INCREMENT PRIMARY KEY, service_created TIMESTAMP DEFAULT now(), last_updated TIMESTAMP DEFAULT now() ON UPDATE now(), service_name TEXT, service_type TEXT, service_address TEXT, last_checked_status BOOLEAN, notification_email BOOLEAN, notification_sms BOOLEAN, email TEXT, phone_number TEXT)")
		connection.commit()
		print("Table succesfully created!")

	except pymysql.MySQLError as e:
		if("(1050," in str(e)): #1050 is warning code for table allready exists
			print("Found table!")
		else:
			print(e)

	except Exception as e:
		# Unknown exception
		print(e)
```

**Comment by Travis-Owens** [comment]
Furthermore, we should consider moving this function to a setup file. This function shouldn't be triggered very often.

**Comment by mathisve** [comment]
I don't think we should, we need to run it every time it starts up. It would only make for more files and more files != cleaner code.

**Comment by mathisve** [comment]
Issue has been fixed and merged with main branch. Closing.
