### ISSUE TITLE
HTTP - Status Checking

### ISSUE THREAD

**Issue by Travis-Owens** [Travis-Owens/Service-Status-Checker#2]
Integrate HTTP protocol status checking.

This module should:
- Support both HTTP and HTTPS
- Act according to the response code of the server, ie. 200
- Trigger the notification system when on status change

**Comment by mathisve** [comment]
`check_http` still uses the old `services` form. Therefore it spits out this error:
```
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main().run()
  File "main.py", line 62, in run
    t = Thread(target = method(service).check)
  File "/Users/mathis/Documents/GitHub/Service-Status-Checker/modules/check_http.py", line 11, in __init__
    self.url = service['url']
KeyError: 'url'
```
The correct version (and the version implemented `database.py`) looks like this:
```python
services = {"service_name": "",
                   "service_type":"",
                   "service_address":"",
                   "last_checked_status":False,
                   "notification_email":True,
                   "notification_sms":True,
                   "email":"",
                   "phone":""}
```
The current version of this file still uses `url` instead of `address` due to bad planning.
This should be an easy fix tho.

**Comment by mathisve** [comment]
Also you need to implement all the correct error logging. The errors in your modules aren't reaching the exceptions database.
